### ISSUE TITLE
mmviz does not fucking work

### ISSUE THREAD

**Issue by NZIXVO** [KeppySoftware/OmniMIDI#205]
**Problem**
i cant fucking play midis on mmviz.exe

**Steps to reproduce**
1. Play any MIDI on application mmviz.exe
2. see no notes

**Expected behavior**
see notes

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/84653718/130341231-b0320848-8375-4f8e-a5fb-933f74928271.png)

**Environment**
 - Operating system: Windows 10 Home 20H2
 - CPU: Intel Core I7
 - RAM: 12GB
 - MIDI application: mmviz (Version ?.?.?.?)
 - Version of the driver: 14.6.9

**Additional context**
no

**Comment by KaleidonKep99** [comment]
Closed for profanity.
Learn how to behave on the Internet first, then I'll help you.
