### ISSUE TITLE
batch conversion - everytime have to set vst fx settings manually...

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/OmniMIDI#95]
is there a work around to to select vst fx settings once a midi playlist instead of selecting it every time again?

**Comment by KaleidonKep99** [comment]
OmniMIDI is a *MIDI synthesizer*, the issue is related to **Keppy's MIDI Converter**.
Please post the issue here: https://github.com/KeppySoftware/Keppys-MIDI-Converter/issues

Closed.
