### ISSUE TITLE
random soundfont selection

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/OmniMIDI#96]
would it be possible to select a folder full of soundfonts and randomly select a soundfont per midi file?

**Comment by KaleidonKep99** [comment]
OmniMIDI is a *MIDI synthesizer*, the issue is related to **Keppy's MIDI Converter**.
Please post the issue here: https://github.com/KeppySoftware/Keppys-MIDI-Converter/issues

Closed.
