### ISSUE TITLE
midi files could not be processed

### ISSUE THREAD

**Issue by ewewo2** [KeppySoftware/OmniMIDI#97]
i have a bunch of midi files which cannot be processed. is there a way to fix it? example file is attached.

[midi.zip](https://github.com/KeppySoftware/OmniMIDI/files/2088160/midi.zip)

**Comment by KaleidonKep99** [comment]
OmniMIDI is a *MIDI synthesizer*, the issue is related to **Keppy's MIDI Converter**.
Please post the issue here: https://github.com/KeppySoftware/Keppys-MIDI-Converter/issues

Closed.
